USE ESCOLA;

INSERT INTO Disciplina (Nome)
VALUES ('MATEMATICA'),
       ('BIOLOGIA'),
       ('DESENHO TECNICO'),
       ('FISICA'),
       ('EDUCACAO FISICA'),
       ('ELETRICIDADE'),
       ('GEOGRAFIA'),
       ('HISTORIA'),
       ('INFORMATICA'),
       ('LABORATORIO ELETRICO'),
       ('INGLES'),
       ('PORTUGUES'),
       ('LITERATURA'),
       ('ORGANIZACOES E NORMAS'),
       ('PRODUCAO ORAL E ESCRITA'),
       ('QUIMICA'),
       ('RESISTENCIA DOS MATERIAS'),
       ('SOCIOLOGIA'),
       ('ELETRONICA'),
       ('INSTALACOES ELETRICAS'),
       ('MEDIDAS ELETRICAS'),
       ('PSICOLOGIA'),
       ('MAQUINAS ELETRICAS'),
       ('PROTECAO E SUBESTACAO'),
       ('REDES DE DISTRIBUICAO'),
       ('SEGURANCA, MEIO AMBIENTE E SAUDE'),
       ('ARTES VISUAIS'),
       ('MUSICA'),
       ('ESPANHOL'),
       ('FRANCES'),
       ('MANDARIM'),
       ('ARTES');
