USE ESCOLA;

INSERT INTO Pessoa (Nome)
VALUES ('RIO DE JANEIRO'),
       ('BELFORD ROXO'),
       ('DUQUE DE CAXIAS'),
       ('GUAPIMIRIM'),
       ('ITABORAI'),
       ('ITAGUAI'),
       ('JAPERI'),
       ('MAGE'),
       ('MARICA'),
       ('MESQUITA'),
       ('NILOPOLIS'),
       ('NITEROI'),
       ('NOVA IGUACU'),
       ('PARACAMBI'),
       ('PETROPOLIS'),
       ('QUEIMADOS'),
       ('SEROPEDICA'),
       ('SAO GONCALO'),
       ('SAO JOAO DE MERITI'),
       ('TANGUA'),
       ('CACHOEIRAS DE MACACU'),
       ('RIO BONITO');
